{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b27b1989-f57f-4198-aad5-dd56a60c36f4",
   "metadata": {},
   "outputs": [],
   "source": [
    "''' ------------------Exception Handling Assignment 1 ---------------------\n",
    "Q 1 - What is an exception in Python------------\n",
    "Ans - An exception basically represents an run-time error. In Python, it is an event which occurs during the \n",
    "execution of the program when python faces a situation that it cannot cope with and the normal flow of program \n",
    "instructions get disrupted.\n",
    "\n",
    "Difference between syntax error and exception -\n",
    "\n",
    "Syntax Error - An syntax error occurs when a statement or expresssion doesnot obeys the rules of the programming \n",
    "language. These errors are generally detected during by the compiler or interpreter while compiling or execution \n",
    "of the program. These errors generally occur due to typing errors, incorrect syntax etc.\n",
    "\n",
    "Exception - An exception is an abnormal event which occurs during the execution of the program. It is an error \n",
    "occuring due to a run-time situation like division by zero, file not found, index out-of bound or attribute error \n",
    "etc arisen while executing the program.\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c1071033-1106-4f4a-b020-a59da98065a0",
   "metadata": {},
   "outputs": [],
   "source": [
    "''' Q 2 - What happens when an exception is not handled?---------------\n",
    "Ans - If an exception occurs during execution of the program code and this exception is not handled, the program \n",
    "gets terminated abruptly and the remaining code after the code causing the exception will not be executed.\n",
    "Example - \n",
    "'''\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"test.log\", level=logging.DEBUG, format=\"%(asctime)s %(message)s\")\n",
    "x = 10\n",
    "y = 0\n",
    "z = 0\n",
    "z = x/y\n",
    "logging.info(\"X = {}, Y = {}, Z = {}\".format(x,y,z))\n",
    "logging.shutdown()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1815a4ae-8577-4d4b-95b3-4f4372fc3a79",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q 3 - Which python statements are used to -------------\n",
    "Ans  - Try block is used in python to catch the exceptions.\n",
    "Exception block is used in python to handle the exceptions.\n",
    "'''\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"test.log\", level=logging.DEBUG, format=\"%(asctime)s %(message)s\")\n",
    "try:\n",
    "    x = 10\n",
    "    y = 0\n",
    "    z = 0\n",
    "    z = x/y\n",
    "    logging.info(\"X = {}, Y = {}, Z = {}\".format(x,y,z))\n",
    "except ZeroDivisionError as e:\n",
    "    logging.error(\"{} divided by zero.\".format(x))\n",
    "finally:\n",
    "    logging.info(\"Execution completed.\")\n",
    "    logging.shutdown()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5e64c0ab-298d-47cc-8ba6-7545fe9c1655",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q 4 - Explain with example ---------------\n",
    "Ans - \n",
    "try - try block is used to catch the exceptions. Program code is placed inside the try block to test it for errors.\n",
    "If any exception occurs during the execution of the code, it will throw the exception in the except block to handle\n",
    "the exception. \n",
    "\n",
    "else - else block is used to place the code that will be exceuted only in case when no exception has been raised in\n",
    "the try block during execution of the program. If any exception is raised during the execution in try block, then \n",
    "else block will not be executed.\n",
    "\n",
    "finally - finally block is a block which will be executed in all situations. So this block is used to place that \n",
    "code which has to be executed in all situations whether an exception is raised or not.\n",
    "\n",
    "raise - raise keyword raises an exception. It is generally used to raise a user customized exception. \n",
    "'''\n",
    "import logging\n",
    "logging.basicConfig(filename=\"test.log\", level=logging.DEBUG, format=\"%(asctime)s %(message)s\")\n",
    "\n",
    "class vote_validation(Exception):\n",
    "    def __init__(self, msg):\n",
    "        self.msg = msg\n",
    "\n",
    "def validate_vote(age, name):\n",
    "    if age < 0 :\n",
    "        raise vote_validation(\"Age cannot be negative.\")\n",
    "    elif age < 18:\n",
    "        raise vote_validation(\"Sorry {}, you are a minor. You cannot cast vote.\".format(name))\n",
    "    else:\n",
    "        logging.info(\"Congrats {}, you are eligible to cast your vote.\".format(name))\n",
    "\n",
    "try:\n",
    "    name = input(\"Enter your name = \")\n",
    "    age = int(input(\"Enter your age : \"))\n",
    "    validate_vote(age, name)\n",
    "\n",
    "except vote_validation as e:\n",
    "    logging.error(e)\n",
    "    \n",
    "else:\n",
    "    logging.info(\"Vote casted successfully.\")\n",
    "    \n",
    "finally:\n",
    "    logging.info(\"Execution completed.\")\n",
    "    logging.shutdown()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72ab74e3-06d4-4fc1-9bda-7424f6fbaa8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q 5 - What are custom exception in python?-------------\n",
    "Ans - \n",
    "Custom Exceptions - A custom exception in python is a user defined exception that is created by the programmer.\n",
    "\n",
    "Need for Custom Exceptions - Custom exceptions are important tool for handling errors related to application \n",
    "specific requirements. Custom exceptions help in making code readable and maintainable, enforcing design patterns,\n",
    "precise error reporting and enhancing code documentation.\n",
    "'''\n",
    "import logging\n",
    "logging.basicConfig(filename=\"test.log\", level=logging.DEBUG, format=\"%(asctime)s %(message)s\")\n",
    "\n",
    "class FahrenError(Exception):\n",
    "    def __init__(self, msg):\n",
    "        self.msg = msg\n",
    "\n",
    "def validate_fahren(f):\n",
    "    if f<32 or f>212:\n",
    "        raise FahrenError(\"{} not in the range(32,212)\".format(f))\n",
    "    else:\n",
    "        logging.info(\"{} is in valid range.\".format(f))\n",
    "\n",
    "try:\n",
    "    fah = int(input(\"Enter temprature in fahrenheit : \"))\n",
    "    validate_fahren(fah)\n",
    "    cel = (fah - 32) * 5 / 9\n",
    "    logging.info(\"{} fahrenheit is equivalent to {} celcius.\".format(fah,cel))\n",
    "    \n",
    "except FahrenError as e:\n",
    "    logging.error(e)\n",
    "\n",
    "finally:\n",
    "    logging.info(\"Execution completed.\")\n",
    "    logging.shutdown()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fb6afb6b-3b90-427b-8df1-8d6febe784c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Q 6 - Create a custom exception class--------------------\n",
    "Ans -\n",
    "'''\n",
    "import logging\n",
    "logging.basicConfig(filename=\"test.log\", level=logging.DEBUG, format=\"%(asctime)s %(message)s\")\n",
    "\n",
    "LogBook = {\n",
    "    \"sahil@gmail.com\" : \"Sahil Verma\",\n",
    "    \"zeenat@gmail.com\" : \"Zeenat Malik\",\n",
    "    \"roza@gmail.com\" : \"Roza D/Souza\",\n",
    "    \"somesh@gmail.com\" : \"Somesh Gupta\",\n",
    "    \"pramod@gmail.com\" : \"Pramod Sharma\",\n",
    "    \"lalit@gmail.com\" : \"Lalit Sen\",\n",
    "    \"jatin@gmail.com\" : \"Jatin Mehta\"\n",
    "}\n",
    "\n",
    "class UserNotFound(Exception):\n",
    "    def __init__(self):\n",
    "        super().__init__(\"Cannot find such user.\")\n",
    "\n",
    "class checkUser(UserNotFound):\n",
    "        \n",
    "    def searchUser(self, uname):\n",
    "        if uname in LogBook:\n",
    "            logging.info(\"{} is a registered user.\".format(LogBook.get(uname)))\n",
    "        else:\n",
    "            raise UserNotFound()\n",
    "\n",
    "try:\n",
    "    temp = checkUser()\n",
    "    temp.searchUser(\"pramod@gmail.com\")\n",
    "    temp.searchUser(\"ajay@gmail.com\")\n",
    "    temp.searchUser(\"anmol@gmail.com\")\n",
    "\n",
    "except UserNotFound as e:\n",
    "    logging.error(e)\n",
    "\n",
    "finally:\n",
    "    logging.info(\"Execution completed.\")\n",
    "    logging.shutdown()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
